apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: akka-cluster-demo
  name: akka-cluster-demo
spec:
  replicas: 3
  selector:
    matchLabels:
     app: akka-cluster-demo

  template:
    metadata:
      labels:
        app: akka-cluster-demo
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: "8080"
        traffic.sidecar.istio.io/excludeOutboundPorts: "2552,8558"
    spec:
      containers:
      - name: akka-cluster-demo
        image: jamesroper/akka-cluster-demo:1.0.3
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # akka-management bootstrap
        - name: management
          containerPort: 8558
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
          periodSeconds: 2
          failureThreshold: 20
          initialDelaySeconds: 2
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          periodSeconds: 2
          failureThreshold: 20
          initialDelaySeconds: 2

